vich_uploader:
    db_driver: orm

    mappings:
        aliment_image:
            uri_prefix: /img/aliments
            upload_destination: '%kernel.project_dir%/public/img/aliments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        type_image:
            uri_prefix: /img/types
            upload_destination: '%kernel.project_dir%/public/img/types'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer